// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDiffEntry } from "./ProjectDiffEntry";

export type ProjectDiffs = { name: string, diffs: Array<ProjectDiffEntry>, };
